ARG NODE_VERSION="20.11.0"
ARG PNPM_VERSION="9.15.3"

##
# Create base image with pnpm installed
##

FROM node:${NODE_VERSION}-alpine as jkomyno-pnpm
LABEL byb/exercise.name=pnpm

RUN apk add git
RUN apk add --no-cache --upgrade grep
RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store \
  npm i -g pnpm@${PNPM_VERSION}

WORKDIR /app

COPY ["./*.json", "./*.yaml", "./"]
